<?php

use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->delete();

        $languages = [
            array('name' => 'ActionScript 3.0','release_year' => 2004,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Ada','release_year' => 1992,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Aldor','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'ALGOL 58','release_year' => 1958,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'ALGOL 60','release_year' => 1960,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'ALGOL 68','release_year' => 1968,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Ateji PX','release_year' => 1,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'APL','release_year' => 1960,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Assembly language','release_year' => 1950,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'AutoHotkey','release_year' => 2003,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'AutoIt','release_year' => 1995,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Bash','release_year' => 1989,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'BASIC','release_year' => 1964,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'BBj','release_year' => 1,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'BeanShell','release_year' => 1999,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 1),
            array('name' => 'BitC','release_year' => 2004,'imperative' => 1,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'BLISS','release_year' => 1970,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'BlitzMax','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Blue','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Boo','release_year' => 1,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Bro','release_year' => 1,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'C','release_year' => 1969,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'C++','release_year' => 1979,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'C#','release_year' => 1999,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Clarion','release_year' => 1986,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Clean','release_year' => 1,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Clojure','release_year' => 2000,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'CLU','release_year' => 1974,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'COBOL','release_year' => 1950,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Cobra','release_year' => 2008,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'ColdFusion (CFML)','release_year' => 1998,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Common Lisp','release_year' => 1980,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'COMAL 80','release_year' => 1973,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Crystal','release_year' => 2011,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Cython','release_year' => 2007,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'D','release_year' => 2001,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Dart','release_year' => 2011,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Dylan','release_year' => 1990,'imperative' => 0,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Eiffel','release_year' => 1985,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Elixir','release_year' => 1,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Erlang','release_year' => 1988,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Euphoria','release_year' => 1993,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Factor','release_year' => 2003,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Falcon','release_year' => 2002,'imperative' => 0,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'FP','release_year' => 1977,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'F#','release_year' => 2005,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Forth','release_year' => 1968,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Fortran','release_year' => 1950,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'FreeBASIC','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'G2','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Gambas','release_year' => 1999,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Game Maker Language','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'GLBasic','release_year' => 2014,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Go','release_year' => 2009,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Gosu','release_year' => 2002,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'GraphTalk','release_year' => 1959,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Groovy','release_year' => 2003,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Harbour','release_year' => 1980,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Haskell','release_year' => 1985,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Haxe','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'HyperNext','release_year' => 1,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'HyperTalk','release_year' => 1987,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Io','release_year' => 2002,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'ISLISP','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'J','release_year' => 1990,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'JADE','release_year' => 1996,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Java','release_year' => 1991,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Julia','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'JavaScript','release_year' => 1993,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Joy','release_year' => 1,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'K','release_year' => 1993,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Kotlin','release_year' => 2012,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'LabVIEW (G)','release_year' => 1986,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Lisp','release_year' => 1958,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'LiveCode','release_year' => 2001,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Logtalk','release_year' => 1,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Lua','release_year' => 1993,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Maple','release_year' => 1982,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Mathematica','release_year' => 1988,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'MATLAB','release_year' => 1984,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Modula-2','release_year' => 1977,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Modula-3','release_year' => 1980,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'MUMPS (M)','release_year' => 1966,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Nim','release_year' => 2008,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Oberon','release_year' => 1986,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Object Pascal','release_year' => 1986,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Objective-C','release_year' => 1984,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'OCaml','release_year' => 1996,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Occam','release_year' => 1983,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Opa','release_year' => 2011,'imperative' => 1,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Oxygene','release_year' => 2011,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Oz-Mozart','release_year' => 1991,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Pascal','release_year' => 1970,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Perl','release_year' => 1987,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'PHP','release_year' => 1995,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'PL/I','release_year' => 1964,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Plus','release_year' => 1976,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Prolog','release_year' => 1972,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'PureBasic','release_year' => 1998,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Python','release_year' => 1991,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 1),
            array('name' => 'R','release_year' => 1993,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Racket','release_year' => 1994,'imperative' => 0,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'REALbasic','release_year' => 1997,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'REBOL','release_year' => 1997,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'RPG','release_year' => 1959,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Ruby','release_year' => 1995,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Rust','release_year' => 2010,'imperative' => 1,'object_oriented' => 0,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'S','release_year' => 1976,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'S-Lang','release_year' => 1991,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Scala','release_year' => 2004,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Scheme','release_year' => 1970,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Seed7','release_year' => 2005,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Simula','release_year' => 1965,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 1),
            array('name' => 'Small Basic','release_year' => 2008,'imperative' => 1,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Smalltalk','release_year' => 1972,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 1,'standarized' => 1),
            array('name' => 'S0BOL','release_year' => 1962,'imperative' => 0,'object_oriented' => 0,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Standard ML','release_year' => 1,'imperative' => 1,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
            array('name' => 'Swift','release_year' => 2014,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Tcl','release_year' => 1988,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Visual Basic','release_year' => 1991,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 1,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Visual Basic .NET','release_year' => 2001,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 1,'reflective' => 1,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Visual FoxPro','release_year' => 1984,'imperative' => 0,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Visual Prolog','release_year' => 1,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 1,'standarized' => 0),
            array('name' => 'Windows PowerShell','release_year' => 2006,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 1,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Wolfram Language','release_year' => 1988,'imperative' => 1,'object_oriented' => 1,'functional' => 1,'procedural' => 1,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'XL','release_year' => 2000,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 0),
            array('name' => 'Xojo','release_year' => 1997,'imperative' => 1,'object_oriented' => 1,'functional' => 0,'procedural' => 1,'generic' => 0,'reflective' => 1,'event_driven' => 1,'standarized' => 0),
            array('name' => 'XPath/XQuery','release_year' => 2007,'imperative' => 0,'object_oriented' => 0,'functional' => 1,'procedural' => 0,'generic' => 0,'reflective' => 0,'event_driven' => 0,'standarized' => 1),
        ];
        DB::table('languages')->insert($languages);
    }
}
