<?php

use Illuminate\Database\Seeder;

class UseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('languages')->delete();
        $uses = [
            array('description' => 'Application'),
            array('description' => 'Artificial Intelligence'),
            array('description' => 'Automation'),
            array('description' => 'Business'),
            array('description' => 'Client-side'),
            array('description' => 'Data processing'),
            array('description' => 'Databases'),
            array('description' => 'Distributed'),
            array('description' => 'Domain specific'),
            array('description' => 'Education'),
            array('description' => 'Embedded'),
            array('description' => 'Expert system'),
            array('description' => 'Game'),
            array('description' => 'General'),
            array('description' => 'Inference'),
            array('description' => 'IoT'),
            array('description' => 'Mobile'),
            array('description' => 'Numerical Computing'),
            array('description' => 'Parallel application'),
            array('description' => 'RAD'),
            array('description' => 'Realtime'),
            array('description' => 'Research'),
            array('description' => 'Scripting'),
            array('description' => 'Server-side'),
            array('description' => 'Shell'),
            array('description' => 'Statistics'),
            array('description' => 'Symbolic computing'),
            array('description' => 'System development'),
            array('description' => 'Technical Computing'),
            array('description' => 'Web')
        ];

        DB::table('uses')->insert($uses);

        // Pivot table
        DB::table('language_use')->delete();
        $l_uses = [
            array('lang_id' => 1, 'use_id' => 1),
            array('lang_id' => 1, 'use_id' => 5),
            array('lang_id' => 1, 'use_id' => 30),
            array('lang_id' => 2, 'use_id' => 1),
            array('lang_id' => 2, 'use_id' => 11),
            array('lang_id' => 2, 'use_id' => 21),
            array('lang_id' => 2, 'use_id' => 28),
            array('lang_id' => 3, 'use_id' => 9),
            array('lang_id' => 3, 'use_id' => 27),
            array('lang_id' => 4, 'use_id' => 1),
            array('lang_id' => 5, 'use_id' => 1),
            array('lang_id' => 6, 'use_id' => 1),
            array('lang_id' => 7, 'use_id' => 19),
            array('lang_id' => 8, 'use_id' => 1),
            array('lang_id' => 8, 'use_id' => 6),
            array('lang_id' => 9, 'use_id' => 14),
            array('lang_id' => 10, 'use_id' => 3),
            array('lang_id' => 10, 'use_id' => 9),
            array('lang_id' => 11, 'use_id' => 3),
            array('lang_id' => 11, 'use_id' => 9),
            array('lang_id' => 12, 'use_id' => 23),
            array('lang_id' => 12, 'use_id' => 25),
            array('lang_id' => 13, 'use_id' => 1),
            array('lang_id' => 13, 'use_id' => 10),
            array('lang_id' => 14, 'use_id' => 1),
            array('lang_id' => 14, 'use_id' => 4),
            array('lang_id' => 14, 'use_id' => 30),
            array('lang_id' => 15, 'use_id' => 1),
            array('lang_id' => 15, 'use_id' => 23),
            array('lang_id' => 16, 'use_id' => 28),
            array('lang_id' => 17, 'use_id' => 28),
            array('lang_id' => 18, 'use_id' => 1),
            array('lang_id' => 18, 'use_id' => 13),
            array('lang_id' => 19, 'use_id' => 10),
            array('lang_id' => 20, 'use_id' => 1),
            array('lang_id' => 21, 'use_id' => 1),
            array('lang_id' => 21, 'use_id' => 9),
            array('lang_id' => 22, 'use_id' => 1),
            array('lang_id' => 22, 'use_id' => 14),
            array('lang_id' => 22, 'use_id' => 28),
            array('lang_id' => 23, 'use_id' => 1),
            array('lang_id' => 23, 'use_id' => 28),
            array('lang_id' => 24, 'use_id' => 1),
            array('lang_id' => 24, 'use_id' => 4),
            array('lang_id' => 24, 'use_id' => 5),
            array('lang_id' => 24, 'use_id' => 14),
            array('lang_id' => 24, 'use_id' => 20),
            array('lang_id' => 24, 'use_id' => 24),
            array('lang_id' => 24, 'use_id' => 30),
            array('lang_id' => 25, 'use_id' => 4),
            array('lang_id' => 25, 'use_id' => 14),
            array('lang_id' => 25, 'use_id' => 30),
            array('lang_id' => 26, 'use_id' => 14),
            array('lang_id' => 27, 'use_id' => 14),
            array('lang_id' => 28, 'use_id' => 14),
            array('lang_id' => 29, 'use_id' => 1),
            array('lang_id' => 29, 'use_id' => 4),
            array('lang_id' => 30, 'use_id' => 1),
            array('lang_id' => 30, 'use_id' => 4),
            array('lang_id' => 30, 'use_id' => 14),
            array('lang_id' => 30, 'use_id' => 30),
            array('lang_id' => 31, 'use_id' => 30),
            array('lang_id' => 32, 'use_id' => 14),
            array('lang_id' => 33, 'use_id' => 10),
            array('lang_id' => 34, 'use_id' => 15),
            array('lang_id' => 35, 'use_id' => 1),
            array('lang_id' => 35, 'use_id' => 14),
            array('lang_id' => 35, 'use_id' => 18),
            array('lang_id' => 36, 'use_id' => 1),
            array('lang_id' => 36, 'use_id' => 28),
            array('lang_id' => 37, 'use_id' => 1),
            array('lang_id' => 37, 'use_id' => 16),
            array('lang_id' => 37, 'use_id' => 17),
            array('lang_id' => 37, 'use_id' => 24),
            array('lang_id' => 37, 'use_id' => 30),
            array('lang_id' => 38, 'use_id' => 1),
            array('lang_id' => 39, 'use_id' => 14),
            array('lang_id' => 39, 'use_id' => 1),
            array('lang_id' => 39, 'use_id' => 4),
            array('lang_id' => 39, 'use_id' => 5),
            array('lang_id' => 39, 'use_id' => 24),
            array('lang_id' => 39, 'use_id' => 30),
            array('lang_id' => 40, 'use_id' => 1),
            array('lang_id' => 40, 'use_id' => 8),
            array('lang_id' => 41, 'use_id' => 1),
            array('lang_id' => 41, 'use_id' => 8),
            array('lang_id' => 42, 'use_id' => 1),
            array('lang_id' => 44, 'use_id' => 1),
            array('lang_id' => 44, 'use_id' => 14),
            array('lang_id' => 46, 'use_id' => 1),
            array('lang_id' => 47, 'use_id' => 14),
            array('lang_id' => 48, 'use_id' => 1),
            array('lang_id' => 48, 'use_id' => 18),
            array('lang_id' => 49, 'use_id' => 1),
            array('lang_id' => 49, 'use_id' => 18),
            array('lang_id' => 50, 'use_id' => 1),
            array('lang_id' => 50, 'use_id' => 12),
            array('lang_id' => 50, 'use_id' => 15),
            array('lang_id' => 51, 'use_id' => 1),
            array('lang_id' => 52, 'use_id' => 1),
            array('lang_id' => 52, 'use_id' => 13),
            array('lang_id' => 53, 'use_id' => 1),
            array('lang_id' => 53, 'use_id' => 13),
            array('lang_id' => 54, 'use_id' => 1),
            array('lang_id' => 54, 'use_id' => 24),
            array('lang_id' => 54, 'use_id' => 30),
            array('lang_id' => 55, 'use_id' => 1),
            array('lang_id' => 55, 'use_id' => 14),
            array('lang_id' => 55, 'use_id' => 23),
            array('lang_id' => 55, 'use_id' => 30),
            array('lang_id' => 56, 'use_id' => 1),
            array('lang_id' => 57, 'use_id' => 1),
            array('lang_id' => 57, 'use_id' => 14),
            array('lang_id' => 57, 'use_id' => 23),
            array('lang_id' => 57, 'use_id' => 30),
            array('lang_id' => 58, 'use_id' => 1),
            array('lang_id' => 58, 'use_id' => 4),
            array('lang_id' => 58, 'use_id' => 6),
            array('lang_id' => 58, 'use_id' => 14),
            array('lang_id' => 58, 'use_id' => 30),
            array('lang_id' => 59, 'use_id' => 1),
            array('lang_id' => 60, 'use_id' => 14),
            array('lang_id' => 60, 'use_id' => 30),
            array('lang_id' => 61, 'use_id' => 1),
            array('lang_id' => 61, 'use_id' => 10),
            array('lang_id' => 62, 'use_id' => 1),
            array('lang_id' => 62, 'use_id' => 14),
            array('lang_id' => 62, 'use_id' => 30),
            array('lang_id' => 63, 'use_id' => 1),
            array('lang_id' => 63, 'use_id' => 23),
            array('lang_id' => 64, 'use_id' => 14),
            array('lang_id' => 65, 'use_id' => 6),
            array('lang_id' => 66, 'use_id' => 1),
            array('lang_id' => 66, 'use_id' => 8),
            array('lang_id' => 67, 'use_id' => 1),
            array('lang_id' => 67, 'use_id' => 4),
            array('lang_id' => 67, 'use_id' => 5),
            array('lang_id' => 67, 'use_id' => 14),
            array('lang_id' => 67, 'use_id' => 17),
            array('lang_id' => 67, 'use_id' => 24),
            array('lang_id' => 67, 'use_id' => 30),
            array('lang_id' => 68, 'use_id' => 14),
            array('lang_id' => 68, 'use_id' => 29),
            array('lang_id' => 69, 'use_id' => 5),
            array('lang_id' => 69, 'use_id' => 24),
            array('lang_id' => 69, 'use_id' => 30),
            array('lang_id' => 70, 'use_id' => 22),
            array('lang_id' => 71, 'use_id' => 6),
            array('lang_id' => 71, 'use_id' => 4),
            array('lang_id' => 73, 'use_id' => 1),
            array('lang_id' => 73, 'use_id' => 3),
            array('lang_id' => 74, 'use_id' => 14),
            array('lang_id' => 75, 'use_id' => 1),
            array('lang_id' => 75, 'use_id' => 14),
            array('lang_id' => 75, 'use_id' => 20),
            array('lang_id' => 76, 'use_id' => 1),
            array('lang_id' => 76, 'use_id' => 2),
            array('lang_id' => 77, 'use_id' => 1),
            array('lang_id' => 77, 'use_id' => 11),
            array('lang_id' => 78, 'use_id' => 18),
            array('lang_id' => 78, 'use_id' => 27),
            array('lang_id' => 79, 'use_id' => 27),
            array('lang_id' => 80, 'use_id' => 1),
            array('lang_id' => 80, 'use_id' => 6),
            array('lang_id' => 80, 'use_id' => 9),
            array('lang_id' => 80, 'use_id' => 22),
            array('lang_id' => 81, 'use_id' => 1),
            array('lang_id' => 81, 'use_id' => 28),
            array('lang_id' => 82, 'use_id' => 1),
            array('lang_id' => 83, 'use_id' => 1),
            array('lang_id' => 83, 'use_id' => 7),
            array('lang_id' => 84, 'use_id' => 1),
            array('lang_id' => 84, 'use_id' => 14),
            array('lang_id' => 84, 'use_id' => 23),
            array('lang_id' => 84, 'use_id' => 28),
            array('lang_id' => 84, 'use_id' => 30),
            array('lang_id' => 85, 'use_id' => 1),
            array('lang_id' => 85, 'use_id' => 28),
            array('lang_id' => 86, 'use_id' => 1),
            array('lang_id' => 86, 'use_id' => 14),
            array('lang_id' => 86, 'use_id' => 17),
            array('lang_id' => 86, 'use_id' => 30),
            array('lang_id' => 87, 'use_id' => 1),
            array('lang_id' => 87, 'use_id' => 14),
            array('lang_id' => 88, 'use_id' => 1),
            array('lang_id' => 89, 'use_id' => 14),
            array('lang_id' => 90, 'use_id' => 30),
            array('lang_id' => 91, 'use_id' => 1),
            array('lang_id' => 92, 'use_id' => 1),
            array('lang_id' => 92, 'use_id' => 8),
            array('lang_id' => 92, 'use_id' => 10),
            array('lang_id' => 93, 'use_id' => 1),
            array('lang_id' => 93, 'use_id' => 10),
            array('lang_id' => 94, 'use_id' => 1),
            array('lang_id' => 94, 'use_id' => 6),
            array('lang_id' => 94, 'use_id' => 23),
            array('lang_id' => 94, 'use_id' => 30),
            array('lang_id' => 95, 'use_id' => 24),
            array('lang_id' => 95, 'use_id' => 30),
            array('lang_id' => 96, 'use_id' => 1),
            array('lang_id' => 97, 'use_id' => 1),
            array('lang_id' => 97, 'use_id' => 28),
            array('lang_id' => 98, 'use_id' => 1),
            array('lang_id' => 98, 'use_id' => 2),
            array('lang_id' => 99, 'use_id' => 1),
            array('lang_id' => 100, 'use_id' => 1),
            array('lang_id' => 100, 'use_id' => 2),
            array('lang_id' => 100, 'use_id' => 14),
            array('lang_id' => 100, 'use_id' => 22),
            array('lang_id' => 100, 'use_id' => 23),
            array('lang_id' => 100, 'use_id' => 30),
            array('lang_id' => 101, 'use_id' => 1),
            array('lang_id' => 101, 'use_id' => 26),
            array('lang_id' => 102, 'use_id' => 10),
            array('lang_id' => 102, 'use_id' => 14),
            array('lang_id' => 102, 'use_id' => 23),
            array('lang_id' => 103, 'use_id' => 1),
            array('lang_id' => 104, 'use_id' => 8),
            array('lang_id' => 105, 'use_id' => 1),
            array('lang_id' => 105, 'use_id' => 28),
            array('lang_id' => 106, 'use_id' => 1),
            array('lang_id' => 106, 'use_id' => 23),
            array('lang_id' => 106, 'use_id' => 30),
            array('lang_id' => 107, 'use_id' => 1),
            array('lang_id' => 107, 'use_id' => 28),
            array('lang_id' => 108, 'use_id' => 1),
            array('lang_id' => 108, 'use_id' => 26),
            array('lang_id' => 109, 'use_id' => 1),
            array('lang_id' => 109, 'use_id' => 18),
            array('lang_id' => 109, 'use_id' => 23),
            array('lang_id' => 110, 'use_id' => 1),
            array('lang_id' => 110, 'use_id' => 8),
            array('lang_id' => 110, 'use_id' => 30),
            array('lang_id' => 111, 'use_id' => 10),
            array('lang_id' => 111, 'use_id' => 14),
            array('lang_id' => 112, 'use_id' => 1),
            array('lang_id' => 112, 'use_id' => 14),
            array('lang_id' => 112, 'use_id' => 23),
            array('lang_id' => 112, 'use_id' => 30),
            array('lang_id' => 113, 'use_id' => 10),
            array('lang_id' => 113, 'use_id' => 14),
            array('lang_id' => 114, 'use_id' => 1),
            array('lang_id' => 114, 'use_id' => 10),
            array('lang_id' => 114, 'use_id' => 13),
            array('lang_id' => 115, 'use_id' => 1),
            array('lang_id' => 115, 'use_id' => 2),
            array('lang_id' => 115, 'use_id' => 4),
            array('lang_id' => 115, 'use_id' => 10),
            array('lang_id' => 115, 'use_id' => 14),
            array('lang_id' => 115, 'use_id' => 30),
            array('lang_id' => 116, 'use_id' => 6),
            array('lang_id' => 117, 'use_id' => 1),
            array('lang_id' => 118, 'use_id' => 1),
            array('lang_id' => 118, 'use_id' => 14),
            array('lang_id' => 119, 'use_id' => 1),
            array('lang_id' => 119, 'use_id' => 23),
            array('lang_id' => 119, 'use_id' => 30),
            array('lang_id' => 120, 'use_id' => 1),
            array('lang_id' => 120, 'use_id' => 3),
            array('lang_id' => 120, 'use_id' => 4),
            array('lang_id' => 120, 'use_id' => 10),
            array('lang_id' => 120, 'use_id' => 14),
            array('lang_id' => 120, 'use_id' => 20),
            array('lang_id' => 121, 'use_id' => 1),
            array('lang_id' => 121, 'use_id' => 4),
            array('lang_id' => 121, 'use_id' => 10),
            array('lang_id' => 121, 'use_id' => 14),
            array('lang_id' => 121, 'use_id' => 20),
            array('lang_id' => 121, 'use_id' => 30),
            array('lang_id' => 122, 'use_id' => 1),
            array('lang_id' => 123, 'use_id' => 1),
            array('lang_id' => 124, 'use_id' => 25),
            array('lang_id' => 125, 'use_id' => 27),
            array('lang_id' => 127, 'use_id' => 1),
            array('lang_id' => 127, 'use_id' => 14),
            array('lang_id' => 127, 'use_id' => 20),
            array('lang_id' => 128, 'use_id' => 6),
            array('lang_id' => 128, 'use_id' => 7),
            array('lang_id' => 128, 'use_id' => 23),
        ];

        DB::table('language_use')->insert($l_uses);
    }
}
